### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by RichardLitt** [jamestalmage/gh-nag#8]
Sometimes, I get an undefined instead of a count. Normally, this is fixed by a refresh. 

<img width="945" alt="screenshot 2016-02-24 13 40 15" src="https://cloud.githubusercontent.com/assets/910753/13296580/383a20e0-dafc-11e5-9ad0-72b9879c7553.png">

**Comment by jamestalmage** [comment]
@RichardLitt - Have you added a token in options? I think I've seen that with rate limiting.

**Comment by RichardLitt** [comment]
Yes, I have done that. Maybe I am using it too much?

**Comment by jamestalmage** [comment]
No, I rarely see that. And I use it quite a bit. 

What are your actual stats? Maybe it's because you've got more than 100 issues or more than 100 PR's? That would require multiple "pages" of results for each request (each GH request delivers 100 items max, and you have to do multiple requests to get the entire list).

**Comment by RichardLitt** [comment]
Hmm. 

Currently, I am at 1 PR and 114 issues.

**Comment by jamestalmage** [comment]
Hmm. So you would have one additional request beyond what I see each time. I doubt that's enough to hit rate limiting, but maybe.

**Comment by jamestalmage** [comment]
I'm wrong anyways. I only fetch once: https://github.com/jamestalmage/gh-nag/blob/master/app/scripts/contentscript.js#L96

**Comment by RichardLitt** [comment]
I'll let you know if this happens again. let's wait a bit, it has been a while since I've seen it. Close this in one month if no repeat.
